package org.mrpaulwoods.springaiintro.sec69.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.mrpaulwoods.springaiintro.sec69.model.Question;
import org.springframework.ai.chat.messages.SystemMessage;
import org.springframework.ai.chat.messages.UserMessage;
import org.springframework.ai.chat.model.ChatModel;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.ai.content.Media;
import org.springframework.ai.image.ImagePrompt;
import org.springframework.ai.openai.OpenAiChatOptions;
import org.springframework.ai.openai.OpenAiImageModel;
import org.springframework.ai.openai.OpenAiImageOptions;
import org.springframework.ai.openai.api.OpenAiApi;
import org.springframework.stereotype.Service;
import org.springframework.util.MimeTypeUtils;
import org.springframework.web.multipart.MultipartFile;

import java.util.Base64;
import java.util.List;

@Service
@Slf4j
@RequiredArgsConstructor
public class OpenAIServiceImpl implements OpenAIService {

    private final OpenAiImageModel imageModel;
    private final ChatModel chatModel;

    @Override
    public byte[] getImage(Question question) {

        var options = OpenAiImageOptions.builder()
                .height(1024)
                .width(1024)
                .responseFormat("b64_json")
                .model("dall-e-3") // default is "dall-e-2"
                .quality("hd")  // standard (default), hd   - for dall-e-3
                .style("vivid") // vivid (default), natural
                .build();

        // https://platform.openai.com/docs/api-reference/images/create
        // https://help.openai.com/en/articles/8555480-dalle-3-api

        ImagePrompt imagePrompt = new ImagePrompt(question.question(), options);
        var imageResponse = imageModel.call(imagePrompt);
        return Base64.getDecoder().decode(imageResponse.getResult().getOutput().getB64Json());
    }

    @Override
    public String getDescription(MultipartFile file) {

        OpenAiChatOptions options = OpenAiChatOptions.builder()
                .model(OpenAiApi.ChatModel.GPT_4_1)
                .build();

        SystemMessage systemMessage = SystemMessage.builder()
                .text("Act as a cheerful helpful assistant.")
                .build();

        UserMessage userMessage = UserMessage.builder()
                .text("Explain what do you see in this picture? Also indicate if the image was generated by an AI or not.")
                .media(new Media(MimeTypeUtils.IMAGE_JPEG, file.getResource()))
                .build();

        ChatResponse response = chatModel.call(new Prompt(List.of(userMessage, systemMessage), options));

        return response.getResult().getOutput().getText();
    }

}
